language: python
python:
  - 3.8
  - 3.7
  - 3.6
sudo: required
dist: xenial
install:
  - pip install poetry
  - pip install codecov
  - pip install tox-travis
script:
  - tox
after_success:
  - codecov
